name: Generate Github top languages
description: Generate Github top languages (within your organizations)
branding:
  icon: bar-chart
  color: purple

inputs:
  botName:
    required: false
    default: "Jan Galek"
    description: "Set bot name for contributors"

  botEmail:
    required: false
    default: "ghome.cz@gmail.com"
    description: "Set bot email address for contributors"
  user:
    required: true
    description: "Github UserName"
  limit:
    required: true
    default: 12
    description: "Limit of languages"
  ignoredOrgsFlag:
    required: true
    default: ""
    description: "Comma-separated list of ignored organizations"
  ignoredReposFlag:
    required: true
    default: ""
    description: "Comma-separated list of ignored repositories"
  ignoredLangsFlag:
    required: false
    default: ""
    description: "Comma-separated list of ignored languages"
  withForks:
    required: false
    default: "false"
    description: "Include forked repositories in the analysis (true/false)"
  withStreak:
    required: false
    default: "true"
    description: "Include streak statistics of your github account (true/false)"
  showStats:
    required: false
    default: "true"
    description: "Include statistics of your github account (true/false)"
  statsFeatures:
    required: false
    default: ""
    description: "Comma-separated list of statistics features to include (commits,prs,reviews,issues,stars,repos,followers)"

env:
  GITHUB_TOKEN: "As provided by Github Actions"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --global user.name "$BOT_NAME"
        git config --global user.email "$BOT_EMAIL"
      shell: bash
      env:
        BOT_NAME: ${{ inputs.botName }}
        BOT_EMAIL: ${{ inputs.botEmail }}

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: "1.26"

    - name: Build the Go binary
      run: |
        git clone https://github.com/gouef/githubtoplanguages.git
        cd githubtoplanguages
        make install
        go build -o app .
        cp app ./../app
        cd ..
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: Run the Go binary
      run: |
        args=()
        [ -n "$USER_NAME" ] && args+=("-user=$USER_NAME")
        [ -n "$LANGUAGE_LIMIT" ] && args+=("-limit=$LANGUAGE_LIMIT")
        [ -n "$IGNORED_ORGS" ] && args+=("-ignore-orgs=$IGNORED_ORGS")
        [ -n "$IGNORED_REPOS" ] && args+=("-ignore-repos=$IGNORED_REPOS")
        [ -n "$IGNORED_LANGUAGES" ] && args+=("-ignore-langs=$IGNORED_LANGUAGES")
        [ -n "$WITH_FORKS" ] && args+=("-with-forks=$WITH_FORKS")
        [ -n "$WITH_STREAK" ] && args+=("-with-streak=$WITH_STREAK")
        [ -n "$SHOW_STATS" ] && args+=("-show-stats=$SHOW_STATS")
        [ -n "$STATS_FEATURES" ] && args+=("-stats=$STATS_FEATURES")
        ./app "${args[@]}" "-gh-token=$GITHUB_TOKEN"
        rm -R githubtoplanguages
        rm app
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        USER_NAME: ${{ inputs.user }}
        LANGUAGE_LIMIT: ${{ inputs.limit }}
        IGNORED_ORGS: ${{ inputs.ignoredOrgsFlag }}
        IGNORED_REPOS: ${{ inputs.ignoredReposFlag }}
        IGNORED_LANGUAGES: ${{ inputs.ignoredLangsFlag }}
        WITH_FORKS: ${{ inputs.withForks }}
        WITH_STREAK: ${{ inputs.withStreak }}
        SHOW_STATS: ${{ inputs.showStats }}
        STATS_FEATURES: ${{ inputs.statsFeatures }}

    - name: Commit and push changes
      run: |
        git add ./toplanguages.svg
        if git diff --cached --quiet; then
          echo "Žádné změny, nic k commitování."
        else
          git add .
          git commit -m "[Update] Generate github top language"
          git pull origin "$DEFAULT_BRANCH" && git push origin "HEAD:$DEFAULT_BRANCH"
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
