name: Create Top Languages

on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    botName:
      required: false
      default: "Jan Galek"
      description: "Set bot name for contributors"
    botEmail:
      required: false
      default: "ghome.cz@gmail.com"
      description: "Set bot email address for contributors"
    user:
      required: true
      default: "gouef"
      description: "Github UserName"
    limit:
      required: true
      default: 6
      description: "Limit of languages"
    ignoredOrgsFlag:
      required: true
      default: "wowmua,EpicGames,Go2speak,gothicuef"
      description: "Comma-separated list of ignored organizations"
    ignoredReposFlag:
      required: true
      default: "wowmua/Maps,TroiaStudio/blizzard-api"
      description: "Comma-separated list of ignored repositories"
    ignoredLangsFlag:
      required: true
      default: "OASv3-yaml,OASv2-yaml,Gettext Catalog,YAML,JSON,MiniYAML"
      description: "Comma-separated list of ignored languages"
    withForks:
      required: false
      default: "false"
      description: "Include forked repositories in the analysis (true/false)"
    showStats:
      required: false
      default: "true"
      description: "Include statistics of your github account (true/false)"
    statsFeatures:
      required: false
      default: ""
      description: "Comma-separated list of statistics features to include (commits,prs,reviews,issues,stars,repos,followers)

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run custom action
        uses: gouef/githubtoplanguages@main
        with:
          botName: "Jan Galek"
          botEmail: "ghome.cz@gmail.com"
          user: "JanGalek"
          limit: 6
          ignoredOrgsFlag: "wowmua"
          ignoredReposFlag: "wowmua/Maps"
          ignoredLangsFlag: ""
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}