name: Create Top Languages

on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      botName:
        required: false
        default: "Jan Galek"
        description: "Set bot name for contributors"
      botEmail:
        required: false
        default: "ghome.cz@gmail.com"
        description: "Set bot email address for contributors"
      user:
        required: true
        default: "gouef"
        description: "Github UserName"
      limit:
        required: true
        default: 8
        type: number
        description: "Limit of languages"
      ignoredOrgsFlag:
        required: true
        default: "wowmua,EpicGames,Go2speak,gothicuef"
        description: "Comma-separated list of ignored organizations"
      ignoredReposFlag:
        required: true
        default: "wowmua/Maps,TroiaStudio/blizzard-api"
        description: "Comma-separated list of ignored repositories"
      ignoredLangsFlag:
        required: true
        default: "OASv3-yaml,OASv2-yaml,Gettext Catalog,YAML,JSON,MiniYAML"
        description: "Comma-separated list of ignored languages"
      withForks:
        required: false
        default: "false"
        description: "Include forked repositories in the analysis (true/false)"
      showStats:
        required: false
        default: "true"
        description: "Include statistics of your github account (true/false)"
      statsFeatures:
        required: false
        default: ""
        description: "Comma-separated list of statistics features to include (commits,prs,reviews,issues,stars,repos,followers)"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26"

      - name: Build the Go binary
        run: go build -o app .

      - name: Generate top languages
        run: |
          args=()
          [ -n "${{ inputs.user || 'JanGalek' }}" ] && args+=("-user=${{ inputs.user || 'JanGalek' }}")
          [ -n "${{ inputs.limit || 12 }}" ] && args+=("-limit=${{ inputs.limit || 12 }}")
          [ -n "${{ inputs.ignoredOrgsFlag || 'wowmua' }}" ] && args+=("-ignore-orgs=${{ inputs.ignoredOrgsFlag || 'wowmua' }}")
          [ -n "${{ inputs.ignoredReposFlag || 'wowmua/Maps' }}" ] && args+=("-ignore-repos=${{ inputs.ignoredReposFlag || 'wowmua/Maps' }}")
          [ -n "${{ inputs.ignoredLangsFlag }}" ] && args+=("-ignore-langs=${{ inputs.ignoredLangsFlag }}")
          [ -n "${{ inputs.withForks || 'false' }}" ] && args+=("-with-forks=${{ inputs.withForks || 'false' }}")
          [ -n "${{ inputs.withStreak || 'true' }}" ] && args+=("-with-streak=${{ inputs.withStreak || 'true' }}")
          [ -n "${{ inputs.showStats || 'true' }}" ] && args+=("-show-stats=${{ inputs.showStats || 'true' }}")
          [ -n "${{ inputs.statsFeatures }}" ] && args+=("-stats=${{ inputs.statsFeatures }}")
          ./app "${args[@]}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "Jan Galek"
          git config user.email "ghome.cz@gmail.com"
          git add toplanguages.svg
          if git diff --cached --quiet; then
            echo "Žádné změny, nic k commitování."
          else
            git commit -m "[Update] Generate github top language"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          fi
        shell: bash
